### ISSUE TITLE
Doubts regarding weight function

### ISSUE THREAD

**Issue by DieterDePaepe** [RubenVerborgh/Computing-Interesting-Paths#1]
On the slides, the weight function is defined as follows:

```
predicateScore(e) = 1 – % of triples using the same predicate
weight(e(v, u)) = log(degree(v) + degree(u)) × predicateScore(e)
```

Lets say I have 2 nodes with a single path in between. This path is formed by a unique edge, so it should be very interesting according to the definition used in the slides.

```
predicateScore(e) = 1 - 0.0001% = 0.99999
weight(e(v, u)) = log(D) × 0.99999  (with D being > 2)
```

This means this edge will have a higher weight than more common edges? That doesn't seem right in a context where you're trying to find the shortest path as a means to find interesting paths.

**Comment by RubenVerborgh** [comment]
That's right, thanks!
